/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export interface Questions {
  answer: string
  audio_path_answer: string | null
  audio_path_question: string | null
  created_at: Generated<string>
  id: number
  image_path_answer: string | null
  image_path_question: string | null
  round_id: number
  text: string
  updated_at: Generated<string>
  video_path_answer: string | null
  video_path_question: string | null
}

export interface QuizRounds {
  quiz_id: number
  round_id: number
}

export interface Quizzes {
  created_at: Generated<string>
  date: string | null
  description: string | null
  id: number
  title: string
  updated_at: Generated<string>
}

export interface Rounds {
  created_at: Generated<string>
  description: string | null
  id: number
  image_path: string | null
  title: string
  updated_at: Generated<string>
}

export interface DB {
  questions: Questions
  quiz_rounds: QuizRounds
  quizzes: Quizzes
  rounds: Rounds
}
